M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Wed 17 May 2023 08:32:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-17T08:32:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X28.32Y-191.075
X34.1Y-191.075
T2
X20.832Y-184.1
X20.832Y-191.1
T0
M30
