M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Sun 14 May 2023 19:46:33
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-14T19:46:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
%
G90
G05
T1
X87.33Y-108.075
X93.11Y-108.075
T2
X79.32Y-104.0
X79.32Y-111.0
T0
M30
